services:
  - type: worker
    name: ivasms-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: ADMIN_USER_IDS
        sync: false
      - key: EMAIL
        sync: false
      - key: PASSWORD
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false
